### PR TITLE
CSS tweaks

### LINKED ISSUE #15: Visual hierarchy of headers is weak
e.g. in https://rstudio.github.io/bslib/articles/theming.html#utility-classes:

Screenshot 2021-03-03 at 9 31 10 AM

I find it hard to tell that "Utility classes" is higher in the hierarchy than "Add margin"

### LINKED ISSUE #16: A smidge too much vertical space in the sidebar?
Maybe my eyes are still getting used to it but it feels like there's a bit too much whitespace in this sidebar

Screenshot 2021-03-03 at 9 32 26 AM

It's worse on pages with longer sidebars, like https://rmarkdown.rstudio.com/docs/.

### PR DESCRIPTION
**Pull request by apreshill**
+ smush line height in sidebar, fixes #16
+  tweak heading styling to fix #15

### CODE REVIEW

**Comment by apreshill** [comment]
@hadley not getting a deploy preview so sharing screenshots:
Screen Shot 2021-03-05 at 3 37 19 PM
Screen Shot 2021-03-05 at 3 37 41 PM

better / worse / can't tell?

**Comment by hadley** [comment]
Looks better to me

**Comment by cderv** [comment]
@apreshill you now have a deploy preview at https://deploy-preview-17--quillt.netlify.app/

**Comment by apreshill** [comment]
Ah thank you!

**Review by cderv — APPROVED** [review]
LGTM

**Pull request merged**
