### PR TITLE
Change style for inline code in headers

### LINKED ISSUE #24: Size of inline code in headings
image

https://rstudio-education.github.io/gradethis/reference/grade_this-objects.html

### PR DESCRIPTION
**Pull request by cderv**
This fixes #24 

I added an article to test some specific styling that we change

### CODE REVIEW

**Comment by cderv** [comment]
Here is what we get with this change: https://deploy-preview-25--quillt.netlify.app/articles/articles/test-style.html

**Comment by apreshill** [comment]
This looks great (and having a deploy preview is so so great).

Do you think for H3 we should not capitalize the code in the header?
 Or would that look odd as lowercase?

Screen Shot 2021-03-11 at 8 45 29 AM

**Comment by cderv** [comment]
> Or would that look odd as lowercase?

This maybe would look odd with part of the tile upper case and other note... 🤔 

Or maybe not: 
image


All the headers: 
image

**Comment by cderv** [comment]
Looking at all the header at the same time, it maybe better to not force inline code upper case. 

And also because code is case sensitive... camelCase would be bad with this theme I guess. right ?

**Comment by apreshill** [comment]
True, we should probably make all code `text-transform: none`?

**Comment by apreshill** [comment]
I think that looks about as good as it can get! It appears downlit linking isn't activated until you get down to h6, but that is not a bad thing here.

**Comment by gadenbuie** [comment]
Thanks for the quick fix @cderv and @apreshill!

**Pull request merged**
